// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/3D" | "/admin" | "/bazi" | "/beast-game" | "/beast-game/battlefield" | "/beast-game/lineup" | "/beast-game/preview" | "/beast-game/production" | "/beast-game/qa-stakes" | "/card-battle-v1" | "/dual-chart" | "/ghost-asura" | "/ghost-asura/cross-device-monitor" | "/ghost-asura/skill" | "/growth-center" | "/insight" | "/internal/orb-material-review" | "/landing" | "/match" | "/music" | "/nameology" | "/numerology" | "/platform-center" | "/platform-control-center" | "/red-luan-heartbeat" | "/single-shensha" | "/star-beasts" | "/tarot" | "/trust" | "/zodiac"
type AppRouteHandlerRoutes = "/api/admin/dual-chart-logs" | "/api/admin/ip-check" | "/api/admin/login" | "/api/admin/logout" | "/api/ai-action-guidance" | "/api/ai-copywriting-style-center" | "/api/ai-follow-up" | "/api/ai-like" | "/api/ai-suggestion" | "/api/analysis/jobs" | "/api/analysis/jobs/[jobId]" | "/api/analysis/results/[resultId]" | "/api/analyze" | "/api/audio/guide/[cardId]" | "/api/bazi" | "/api/bazi-debug" | "/api/bazi/google-reading" | "/api/bazi/horror-reading" | "/api/beast-game" | "/api/beast-game/battlefield" | "/api/beast-game/elements" | "/api/beast-game/guide-book" | "/api/beast-game/stake-duel" | "/api/beast-game/starter-pack" | "/api/beast-game/turns" | "/api/beast-production" | "/api/beast-skills" | "/api/credibility" | "/api/dual-chart" | "/api/dual-chart/session" | "/api/ghost-asura/reading" | "/api/ghost-asura/timeline" | "/api/ghost-asura/validate-consistency" | "/api/growth-center" | "/api/home-trust" | "/api/home-trust/agree" | "/api/home-trust/disagree" | "/api/home-trust/feedback" | "/api/home-trust/feedback/stats" | "/api/home-trust/view" | "/api/insight-analyze" | "/api/karma-story-generate" | "/api/master-platform-final-optimize" | "/api/match-generate" | "/api/music-elevenlabs" | "/api/music-generate" | "/api/music-lyria" | "/api/nameology-analyze" | "/api/number-fortune" | "/api/number/analyze" | "/api/platform-center" | "/api/platform-control-center" | "/api/preview" | "/api/red-luan-heartbeat" | "/api/solar-term" | "/api/star-beasts/guardian" | "/api/taiji-sound-preference" | "/api/tarot/deck" | "/api/tarot/draw-output" | "/api/tarot/interpret" | "/api/tarot/reading" | "/api/tarot/shuffle" | "/api/tarot/stats" | "/api/trust-feedback/ws" | "/api/visitor/record" | "/api/ziwei-debug" | "/api/ziwei/[analysisId]/entertainment-analysis" | "/api/ziwei/[analysisId]/teacher-analysis" | "/internal/health/dependencies" | "/internal/health/live" | "/internal/health/ready"
type PageRoutes = never
type LayoutRoutes = "/" | "/beast-game" | "/red-luan-heartbeat"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/3D": {}
  "/admin": {}
  "/api/admin/dual-chart-logs": {}
  "/api/admin/ip-check": {}
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/ai-action-guidance": {}
  "/api/ai-copywriting-style-center": {}
  "/api/ai-follow-up": {}
  "/api/ai-like": {}
  "/api/ai-suggestion": {}
  "/api/analysis/jobs": {}
  "/api/analysis/jobs/[jobId]": { "jobId": string; }
  "/api/analysis/results/[resultId]": { "resultId": string; }
  "/api/analyze": {}
  "/api/audio/guide/[cardId]": { "cardId": string; }
  "/api/bazi": {}
  "/api/bazi-debug": {}
  "/api/bazi/google-reading": {}
  "/api/bazi/horror-reading": {}
  "/api/beast-game": {}
  "/api/beast-game/battlefield": {}
  "/api/beast-game/elements": {}
  "/api/beast-game/guide-book": {}
  "/api/beast-game/stake-duel": {}
  "/api/beast-game/starter-pack": {}
  "/api/beast-game/turns": {}
  "/api/beast-production": {}
  "/api/beast-skills": {}
  "/api/credibility": {}
  "/api/dual-chart": {}
  "/api/dual-chart/session": {}
  "/api/ghost-asura/reading": {}
  "/api/ghost-asura/timeline": {}
  "/api/ghost-asura/validate-consistency": {}
  "/api/growth-center": {}
  "/api/home-trust": {}
  "/api/home-trust/agree": {}
  "/api/home-trust/disagree": {}
  "/api/home-trust/feedback": {}
  "/api/home-trust/feedback/stats": {}
  "/api/home-trust/view": {}
  "/api/insight-analyze": {}
  "/api/karma-story-generate": {}
  "/api/master-platform-final-optimize": {}
  "/api/match-generate": {}
  "/api/music-elevenlabs": {}
  "/api/music-generate": {}
  "/api/music-lyria": {}
  "/api/nameology-analyze": {}
  "/api/number-fortune": {}
  "/api/number/analyze": {}
  "/api/platform-center": {}
  "/api/platform-control-center": {}
  "/api/preview": {}
  "/api/red-luan-heartbeat": {}
  "/api/solar-term": {}
  "/api/star-beasts/guardian": {}
  "/api/taiji-sound-preference": {}
  "/api/tarot/deck": {}
  "/api/tarot/draw-output": {}
  "/api/tarot/interpret": {}
  "/api/tarot/reading": {}
  "/api/tarot/shuffle": {}
  "/api/tarot/stats": {}
  "/api/trust-feedback/ws": {}
  "/api/visitor/record": {}
  "/api/ziwei-debug": {}
  "/api/ziwei/[analysisId]/entertainment-analysis": { "analysisId": string; }
  "/api/ziwei/[analysisId]/teacher-analysis": { "analysisId": string; }
  "/bazi": {}
  "/beast-game": {}
  "/beast-game/battlefield": {}
  "/beast-game/lineup": {}
  "/beast-game/preview": {}
  "/beast-game/production": {}
  "/beast-game/qa-stakes": {}
  "/card-battle-v1": {}
  "/dual-chart": {}
  "/ghost-asura": {}
  "/ghost-asura/cross-device-monitor": {}
  "/ghost-asura/skill": {}
  "/growth-center": {}
  "/insight": {}
  "/internal/health/dependencies": {}
  "/internal/health/live": {}
  "/internal/health/ready": {}
  "/internal/orb-material-review": {}
  "/landing": {}
  "/match": {}
  "/music": {}
  "/nameology": {}
  "/numerology": {}
  "/platform-center": {}
  "/platform-control-center": {}
  "/red-luan-heartbeat": {}
  "/single-shensha": {}
  "/star-beasts": {}
  "/tarot": {}
  "/trust": {}
  "/zodiac": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/beast-game": never
  "/red-luan-heartbeat": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
