// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/3D/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/3D">> = Specific
  const handler = {} as typeof import("../../app/3D/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bazi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bazi">> = Specific
  const handler = {} as typeof import("../../app/bazi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beast-game/battlefield/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beast-game/battlefield">> = Specific
  const handler = {} as typeof import("../../app/beast-game/battlefield/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beast-game/lineup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beast-game/lineup">> = Specific
  const handler = {} as typeof import("../../app/beast-game/lineup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beast-game/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beast-game">> = Specific
  const handler = {} as typeof import("../../app/beast-game/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beast-game/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beast-game/preview">> = Specific
  const handler = {} as typeof import("../../app/beast-game/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beast-game/production/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beast-game/production">> = Specific
  const handler = {} as typeof import("../../app/beast-game/production/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beast-game/qa-stakes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beast-game/qa-stakes">> = Specific
  const handler = {} as typeof import("../../app/beast-game/qa-stakes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/card-battle-v1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/card-battle-v1">> = Specific
  const handler = {} as typeof import("../../app/card-battle-v1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dual-chart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dual-chart">> = Specific
  const handler = {} as typeof import("../../app/dual-chart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ghost-asura/cross-device-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ghost-asura/cross-device-monitor">> = Specific
  const handler = {} as typeof import("../../app/ghost-asura/cross-device-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ghost-asura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ghost-asura">> = Specific
  const handler = {} as typeof import("../../app/ghost-asura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ghost-asura/skill/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ghost-asura/skill">> = Specific
  const handler = {} as typeof import("../../app/ghost-asura/skill/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-center">> = Specific
  const handler = {} as typeof import("../../app/growth-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/insight/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insight">> = Specific
  const handler = {} as typeof import("../../app/insight/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/internal/orb-material-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/internal/orb-material-review">> = Specific
  const handler = {} as typeof import("../../app/internal/orb-material-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/match/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/match">> = Specific
  const handler = {} as typeof import("../../app/match/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/music/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/music">> = Specific
  const handler = {} as typeof import("../../app/music/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nameology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nameology">> = Specific
  const handler = {} as typeof import("../../app/nameology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/numerology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/numerology">> = Specific
  const handler = {} as typeof import("../../app/numerology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform-center">> = Specific
  const handler = {} as typeof import("../../app/platform-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform-control-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform-control-center">> = Specific
  const handler = {} as typeof import("../../app/platform-control-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/red-luan-heartbeat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/red-luan-heartbeat">> = Specific
  const handler = {} as typeof import("../../app/red-luan-heartbeat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/single-shensha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/single-shensha">> = Specific
  const handler = {} as typeof import("../../app/single-shensha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/star-beasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/star-beasts">> = Specific
  const handler = {} as typeof import("../../app/star-beasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tarot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarot">> = Specific
  const handler = {} as typeof import("../../app/tarot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trust">> = Specific
  const handler = {} as typeof import("../../app/trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/zodiac/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/zodiac">> = Specific
  const handler = {} as typeof import("../../app/zodiac/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/dual-chart-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dual-chart-logs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/dual-chart-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/ip-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ip-check">> = Specific
  const handler = {} as typeof import("../../app/api/admin/ip-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-action-guidance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-action-guidance">> = Specific
  const handler = {} as typeof import("../../app/api/ai-action-guidance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-copywriting-style-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-copywriting-style-center">> = Specific
  const handler = {} as typeof import("../../app/api/ai-copywriting-style-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-follow-up/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-follow-up">> = Specific
  const handler = {} as typeof import("../../app/api/ai-follow-up/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-like">> = Specific
  const handler = {} as typeof import("../../app/api/ai-like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai-suggestion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-suggestion">> = Specific
  const handler = {} as typeof import("../../app/api/ai-suggestion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analysis/jobs/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analysis/jobs/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/api/analysis/jobs/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analysis/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analysis/jobs">> = Specific
  const handler = {} as typeof import("../../app/api/analysis/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analysis/results/[resultId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analysis/results/[resultId]">> = Specific
  const handler = {} as typeof import("../../app/api/analysis/results/[resultId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze">> = Specific
  const handler = {} as typeof import("../../app/api/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audio/guide/[cardId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audio/guide/[cardId]">> = Specific
  const handler = {} as typeof import("../../app/api/audio/guide/[cardId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bazi-debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bazi-debug">> = Specific
  const handler = {} as typeof import("../../app/api/bazi-debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bazi/google-reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bazi/google-reading">> = Specific
  const handler = {} as typeof import("../../app/api/bazi/google-reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bazi/horror-reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bazi/horror-reading">> = Specific
  const handler = {} as typeof import("../../app/api/bazi/horror-reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bazi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bazi">> = Specific
  const handler = {} as typeof import("../../app/api/bazi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/battlefield/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game/battlefield">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/battlefield/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/elements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game/elements">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/elements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/guide-book/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game/guide-book">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/guide-book/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/stake-duel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game/stake-duel">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/stake-duel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/starter-pack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game/starter-pack">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/starter-pack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-game/turns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-game/turns">> = Specific
  const handler = {} as typeof import("../../app/api/beast-game/turns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-production/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-production">> = Specific
  const handler = {} as typeof import("../../app/api/beast-production/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beast-skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beast-skills">> = Specific
  const handler = {} as typeof import("../../app/api/beast-skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/credibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credibility">> = Specific
  const handler = {} as typeof import("../../app/api/credibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dual-chart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dual-chart">> = Specific
  const handler = {} as typeof import("../../app/api/dual-chart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dual-chart/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dual-chart/session">> = Specific
  const handler = {} as typeof import("../../app/api/dual-chart/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ghost-asura/reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ghost-asura/reading">> = Specific
  const handler = {} as typeof import("../../app/api/ghost-asura/reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ghost-asura/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ghost-asura/timeline">> = Specific
  const handler = {} as typeof import("../../app/api/ghost-asura/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ghost-asura/validate-consistency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ghost-asura/validate-consistency">> = Specific
  const handler = {} as typeof import("../../app/api/ghost-asura/validate-consistency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/growth-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth-center">> = Specific
  const handler = {} as typeof import("../../app/api/growth-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home-trust/agree/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-trust/agree">> = Specific
  const handler = {} as typeof import("../../app/api/home-trust/agree/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home-trust/disagree/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-trust/disagree">> = Specific
  const handler = {} as typeof import("../../app/api/home-trust/disagree/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home-trust/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-trust/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/home-trust/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home-trust/feedback/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-trust/feedback/stats">> = Specific
  const handler = {} as typeof import("../../app/api/home-trust/feedback/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home-trust/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-trust">> = Specific
  const handler = {} as typeof import("../../app/api/home-trust/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home-trust/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home-trust/view">> = Specific
  const handler = {} as typeof import("../../app/api/home-trust/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/insight-analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insight-analyze">> = Specific
  const handler = {} as typeof import("../../app/api/insight-analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/karma-story-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/karma-story-generate">> = Specific
  const handler = {} as typeof import("../../app/api/karma-story-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/master-platform-final-optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/master-platform-final-optimize">> = Specific
  const handler = {} as typeof import("../../app/api/master-platform-final-optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/match-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/match-generate">> = Specific
  const handler = {} as typeof import("../../app/api/match-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/music-elevenlabs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/music-elevenlabs">> = Specific
  const handler = {} as typeof import("../../app/api/music-elevenlabs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/music-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/music-generate">> = Specific
  const handler = {} as typeof import("../../app/api/music-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/music-lyria/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/music-lyria">> = Specific
  const handler = {} as typeof import("../../app/api/music-lyria/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/nameology-analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nameology-analyze">> = Specific
  const handler = {} as typeof import("../../app/api/nameology-analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/number-fortune/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/number-fortune">> = Specific
  const handler = {} as typeof import("../../app/api/number-fortune/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/number/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/number/analyze">> = Specific
  const handler = {} as typeof import("../../app/api/number/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/platform-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform-center">> = Specific
  const handler = {} as typeof import("../../app/api/platform-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/platform-control-center/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform-control-center">> = Specific
  const handler = {} as typeof import("../../app/api/platform-control-center/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview">> = Specific
  const handler = {} as typeof import("../../app/api/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/red-luan-heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/red-luan-heartbeat">> = Specific
  const handler = {} as typeof import("../../app/api/red-luan-heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/solar-term/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solar-term">> = Specific
  const handler = {} as typeof import("../../app/api/solar-term/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/star-beasts/guardian/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/star-beasts/guardian">> = Specific
  const handler = {} as typeof import("../../app/api/star-beasts/guardian/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/taiji-sound-preference/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taiji-sound-preference">> = Specific
  const handler = {} as typeof import("../../app/api/taiji-sound-preference/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tarot/deck/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/deck">> = Specific
  const handler = {} as typeof import("../../app/api/tarot/deck/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tarot/draw-output/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/draw-output">> = Specific
  const handler = {} as typeof import("../../app/api/tarot/draw-output/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tarot/interpret/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/interpret">> = Specific
  const handler = {} as typeof import("../../app/api/tarot/interpret/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tarot/reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/reading">> = Specific
  const handler = {} as typeof import("../../app/api/tarot/reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tarot/shuffle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/shuffle">> = Specific
  const handler = {} as typeof import("../../app/api/tarot/shuffle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tarot/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tarot/stats">> = Specific
  const handler = {} as typeof import("../../app/api/tarot/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trust-feedback/ws/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trust-feedback/ws">> = Specific
  const handler = {} as typeof import("../../app/api/trust-feedback/ws/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/visitor/record/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/visitor/record">> = Specific
  const handler = {} as typeof import("../../app/api/visitor/record/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ziwei-debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ziwei-debug">> = Specific
  const handler = {} as typeof import("../../app/api/ziwei-debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ziwei/[analysisId]/entertainment-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ziwei/[analysisId]/entertainment-analysis">> = Specific
  const handler = {} as typeof import("../../app/api/ziwei/[analysisId]/entertainment-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ziwei/[analysisId]/teacher-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ziwei/[analysisId]/teacher-analysis">> = Specific
  const handler = {} as typeof import("../../app/api/ziwei/[analysisId]/teacher-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/internal/health/dependencies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/internal/health/dependencies">> = Specific
  const handler = {} as typeof import("../../app/internal/health/dependencies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/internal/health/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/internal/health/live">> = Specific
  const handler = {} as typeof import("../../app/internal/health/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/internal/health/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/internal/health/ready">> = Specific
  const handler = {} as typeof import("../../app/internal/health/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/beast-game/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/beast-game">> = Specific
  const handler = {} as typeof import("../../app/beast-game/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/red-luan-heartbeat/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/red-luan-heartbeat">> = Specific
  const handler = {} as typeof import("../../app/red-luan-heartbeat/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
