-- 【已停用】請勿再執行本檔。
--
-- 正式版本在：supabase/migrations/20261006170000_harden_home_trust_counters.sql
--
-- 本檔原本的內容有三個問題（2026-10-06 在真實 Postgres 引擎上實測確認）：
--   1. 三個累加函式 increment_home_trust_agree／disagree／view 每次呼叫都會報
--      42702 "column reference is ambiguous"，所以 /api/home-trust/* 的累加一律失敗（503）。
--   2. 「Allow rpc increment」策略（FOR UPDATE USING (true)）讓持有公開金鑰的人可以直接把
--      數字改成任意值，違反「客戶端不得指定最終數字」。
--   3. CREATE POLICY 不可重複執行，第二次部署會在中途失敗。
--
-- 若已經執行過本檔：直接套用上面那份遷移即可，它可以從本檔的結果升級，且不會重置任何數字。
