const { astro } = require('iztro');
const c = astro.bySolar('1979-9-2', 2, 'female', true, 'zh-TW'); // 寅時 = index 2
const life = c.palaces.find(p => p.name.trim() === '命宮');
const body = c.palaces.find(p => p.isBodyPalace);
const qy   = c.palaces.find(p => p.name.trim() === '遷移');
const cb   = c.palaces.find(p => p.name.trim() === '財帛');
const gl   = c.palaces.find(p => p.name.trim() === '官祿');
const S = a => a.map(s=>s.name+'('+s.brightness+')').join('、') || '（無主星）';
console.log('=== 引擎輸出 vs 你提供的正確盤 ===');
console.log('命宮干支      :', life.heavenlyStem + life.earthlyBranch, '   | 期望 庚午      =>', (life.heavenlyStem+life.earthlyBranch)==='庚午'?'✅':'❌');
console.log('命宮主星      :', S(life.majorStars), '| 期望 破軍(廟)  =>', S(life.majorStars)==='破軍(廟)'?'✅':'❌');
console.log('身宮          :', body.name + '／' + body.heavenlyStem + body.earthlyBranch, ' | 期望 官祿／甲戌 =>', (body.name.trim()==='官祿'&&body.heavenlyStem+body.earthlyBranch==='甲戌')?'✅':'❌');
console.log('遷移宮主星    :', S(qy.majorStars), '| 期望 廉貞、天相 =>', qy.majorStars.map(s=>s.name).join('、')==='廉貞、天相'?'✅':'❌');
console.log('');
console.log('=== 三方四正（建立在命宮上） ===');
console.log('本宮 命宮:', life.heavenlyStem+life.earthlyBranch, S(life.majorStars));
console.log('三合 財帛:', cb.heavenlyStem+cb.earthlyBranch, S(cb.majorStars));
console.log('三合 官祿:', gl.heavenlyStem+gl.earthlyBranch, S(gl.majorStars));
console.log('對宮 遷移:', qy.heavenlyStem+qy.earthlyBranch, S(qy.majorStars));
console.log('');
console.log('=== 十二宮完整表 ===');
c.palaces.forEach(p => console.log(' ', (p.name.trim()+'　').slice(0,3), p.heavenlyStem+p.earthlyBranch, p.isBodyPalace?'[身宮]':'      ', S(p.majorStars)));
