import assert from 'node:assert/strict';
import {skillProductionRecord} from '../scripts/beast-skill-production-record.mjs';
const id='beast_a01';
const preview=`reports/beast-production/previews/${id}-attempt-01.mp4`;
const native=`.tmp/beast-production/${id}/attempt-01/candidate.mp4`;
const cross=`reports/beast-production/cross-checks/${id}-attempt-01.json`;
const job={cardId:id,reference:'public/beast-game/spirit/01.webp',referenceSha256:'reference',state:'needs-refinement',attempt:1,provider:'gemini-omni-1.1-flash',opponentId:'beast_a02',candidateSha256:'candidate',preview,automaticReview:{checks:{identity:{status:'pass'},tail:{status:'pass'},playerVoice:{status:'pass'}}}};
const data=new Map([[preview,'preview'],[native,'candidate'],[cross,{candidateSha256:'candidate',referenceSha256:'reference',checks:{tail:{status:'fail',evidence:'Tail lost its canonical shape'}},correctionsToModel:'Model overlooked the tail'}]]);
const files={exists:file=>data.has(file),json:file=>structuredClone(data.get(file)),hash:file=>data.get(file),seconds:()=>6};
const registered=skillProductionRecord(job,files);
assert.equal(registered.registrationStatus,'registered');
assert.equal(registered.candidate.access,'local-review-only');
assert.equal(registered.release,undefined);
assert.equal(registered.video,undefined);
assert.equal(registered.review.fullAudiovisualAcceptance,'pending');
assert.ok(registered.review.outstandingChecks.includes('playerVoice'),'A model pass cannot imply audio listening approval');
assert.deepEqual(registered.review.failedParts,[{part:'tail',evidence:'Tail lost its canonical shape'}]);
assert.throws(()=>skillProductionRecord(job,{...files,hash:()=> 'replaced-file'}),/Candidate hash mismatch/);
for(const seconds of [2,NaN,Infinity])assert.throws(()=>skillProductionRecord(job,{...files,seconds:()=>seconds}),/not six seconds/);
assert.equal(skillProductionRecord(job,{...files,exists:file=>file!==preview&&files.exists(file)}).candidate,null);
data.set(cross,{candidateSha256:'older-file',referenceSha256:'reference',checks:{tail:{status:'pass'}}});
const stale=skillProductionRecord(job,files);
assert.equal(stale.review.visualReport,null);
assert.ok(stale.review.outstandingChecks.includes('tail'));
const retry={...job,attempt:2,state:'quota-blocked',candidateSha256:null,opponentId:'beast_a03',history:[job],quota:{scope:'monthly-spend',observedAt:'2026-09-06T03:00:00Z',retryAt:null},providerMessage:'PRIVATE PROVIDER MESSAGE',omniInteractionId:'PRIVATE TASK ID'};
const retained=skillProductionRecord(retry,files);
assert.equal(retained.latestAttempt,2);
assert.equal(retained.candidate.attempt,1);
assert.equal(retained.candidate.opponentId,'beast_a02','Older candidates retain their own opponent');
assert.ok(!JSON.stringify(retained).includes('PRIVATE'));
const preparationReport=`reports/beast-production/${id}-preparation.json`;
const scene=`.tmp/beast-production/${id}/staging/paired-source-v1.png`;
const provenanceReport=`.tmp/beast-production/${id}/staging/provenance.json`;
data.set(scene,'scene-hash');
data.set(preparationReport,{cardId:id,scene,sceneSha256:'scene-hash',imagePrompt:'Original prompt',sceneReview:'Complete source frame'});
data.set(provenanceReport,{playerId:id,opponentId:'beast_a02',canonicalPlayerSha256:'reference',canonicalOpponentSha256:'opponent-reference',sha256:'scene-hash',prompts:['Original prompt'],acceptedForAnimationCandidate:true});
const preparedJob={...job,attempt:undefined,candidateSha256:null,preview:null,state:'awaiting-generation',preparationReport,sceneReference:scene,sceneReferenceSha256:'scene-hash',opponentReferenceSha256:'opponent-reference'};
const prepared=skillProductionRecord(preparedJob,files);
assert.equal(prepared.sourceScene.status,'prepared-for-animation');
assert.equal(prepared.candidate,null,'A prepared still image is never counted as a video');
assert.equal(prepared.latestAttempt,0,'Preparation does not submit a video');
data.get(provenanceReport).prompts=[null];
assert.throws(()=>skillProductionRecord(preparedJob,files),/Source-scene provenance mismatch/);
data.get(provenanceReport).prompts=['Original prompt'];
data.get(preparationReport).imagePrompts=['Original prompt','Framing correction'];
assert.throws(()=>skillProductionRecord(preparedJob,files),/Source-scene provenance mismatch/,'Refinement prompts cannot disappear from provenance');
data.get(provenanceReport).prompts=['Original prompt','Framing correction'];
assert.equal(skillProductionRecord(preparedJob,files).sourceScene.workspaceFile,scene);
data.get(provenanceReport).canonicalOpponentSha256='changed-opponent';
assert.throws(()=>skillProductionRecord(preparedJob,files),/Source-scene provenance mismatch/);
const voicePath=`.tmp/beast-production/${id}/voice/provenance-v2.json`;
data.set(voicePath,{cardId:'beast_a02',source:`public/audio/beast-voices/${id}.mp3`});
assert.throws(()=>skillProductionRecord(job,files),/Voice provenance mismatch/);
console.log('PASS: registration retains verified candidates, rejects replaced/non-six-second assets, preserves historical opponents and never grants audiovisual approval');
