import assert from 'node:assert/strict';
import { newBattle, moveCard, assertOneZone } from '../.beast-game-build/lib/beast-game/battlefield.js';
import { startFromField, fieldFromMatch, autoPlaceOpponent } from '../.beast-game-build/lib/beast-game/battle-bridge.js';
let field = autoPlaceOpponent(newBattle(['beast_a01','beast_a02','beast_a03'], ['beast_a04','beast_a05','beast_a06'], () => .5), () => .5);
field = moveCard(field, 'PLAYER', field.player.hand[0], {zone:'ACTIVE'});
field = moveCard(field, 'PLAYER', field.player.hand[0], {zone:'BENCH',slotIndex:0});
const before = structuredClone(field);
const match = startFromField(field, 42);
match.player.team[0].defeated = true;
match.player.team[0].hp = 0;
match.player.active = 1;
const projected = fieldFromMatch(field, match);
assert.equal(projected.player.active, match.player.team[1].cardId);
assert.ok(projected.player.discard.includes(match.player.team[0].cardId));
assert.deepEqual(field, before);
assertOneZone(projected);
assert.deepEqual(fieldFromMatch(projected, match), projected);
match.status = 'FINISHED';
assert.equal(fieldFromMatch(field, match).phase, 'END');
console.log('PASS: 換陣與倒下同步桌面、棄牌不重複、不修改原佈陣、結束狀態一致');
