import assert from 'node:assert/strict';
const base = process.env.DUAL_CHART_TEST_URL || 'http://localhost:8888';
const password = process.env.DUAL_CHART_PASSWORD;
if (!password) throw new Error('Load the authorized local configuration to run this integration check.');
const input = { birthDate: '1974-07-28', birthTime: '09:30', gender: 'male', calendarType: 'solar', timezone: 'Asia/Taipei' };
const request = (path, body, cookie, origin = base, method = 'POST') => fetch(`${base}${path}`, { method, headers: { 'Content-Type': 'application/json', Origin: origin, ...(cookie ? { Cookie: cookie } : {}) }, ...(method === 'POST' ? { body: JSON.stringify(body) } : {}) });
const locked = await fetch(`${base}/dual-chart`);
assert.equal(locked.status, 200);
assert.ok((await locked.text()).includes('輸入密碼，開啟雙命盤'));
assert.equal((await request('/api/dual-chart', input)).status, 401);
assert.equal((await request('/api/dual-chart/session', { password: 'invalid-test-credential' })).status, 401);
assert.equal((await request('/api/dual-chart/session', { password: 'invalid-test-credential' }, undefined, 'https://outside.example')).status, 403);
const login = await request('/api/dual-chart/session', { password });
assert.equal(login.status, 200, 'Authorized login must succeed');
const setCookie = login.headers.get('set-cookie');
assert.ok(setCookie?.includes('HttpOnly'));
assert.match(setCookie, /SameSite=strict/i);
assert.match(setCookie, /Path=\//i);
const cookie = setCookie.split(';')[0];
const page = await fetch(`${base}/dual-chart`, { headers: { Cookie: cookie } });
assert.ok((await page.text()).includes('出生日期（萬年曆）'));
const result = await request('/api/dual-chart', input, cookie);
assert.equal(result.status, 200);
assert.match(result.headers.get('cache-control'), /no-store/);
const { data } = await result.json();
assert.equal(data.ziwei.palaces.length, 12);
assert.equal(data.ziwei.majorStarPositions.length, 14);
assert.equal(data.bazi.professionalChart.pillarDetails.year.ganzhi, '甲寅');
assert.equal((await request('/api/dual-chart', input, cookie, 'https://outside.example')).status, 403);
for (const change of [{ birthDate: '2023-02-29' }, { birthTime: '' }, { timeUnknown: true }, { gender: 'other' }]) assert.equal((await request('/api/dual-chart', { ...input, ...change }, cookie)).status, 400);
assert.equal((await request('/api/dual-chart', input, 'dual_chart_session=forged')).status, 401);
assert.equal((await request('/api/dual-chart', input, cookie)).status, 200, 'Existing session can generate again without a second password');
const logout = await request('/api/dual-chart/session', undefined, cookie, base, 'DELETE');
assert.match(logout.headers.get('set-cookie'), /Max-Age=0/i);
assert.equal((await request('/api/dual-chart', input)).status, 401);
console.log('PASS: live locked page/API, wrong/correct password, HttpOnly session, single-login reuse, real double charts, invalid inputs, forged cookie, cross-origin and logout cookie.');
