/**
 * 鬼魅阿修羅 — Skill 母版覆蓋率測試（話術完整化）
 * ============================================================================
 * 唯一清單＝後端實際會出現的規則編號（lib/dual-chart-iching-shensha.ts 的 DUAL_SHENSHA_RULES）。
 * 驗證整條鏈：命中 → asuraId → Skill → 既有話術／生成 → 驗證 → 讀盤輸出。
 * RED 樣本：tianyiDoctor、guoyin、xuetang、jiesha、guchen（修前會顯示「此域暫無可用判讀」）；yuede 為正常對照。
 * ============================================================================
 */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const load = require('./helpers/load-iching-shensha-ui.cjs');

const root = path.resolve(__dirname, '..');
const cache = new Map();
const L = (file) => load(file, 'zh-Hant', cache);

const { DUAL_SHENSHA_RULES } = L('lib/dual-chart-iching-shensha.ts');
const { SHENSHA_TEACHER_READINGS } = L('lib/iching-shensha-teacher-readings.ts');
const skill = L('features/ghost-asura/skill/index.ts');
const { translateVerifiedRecords } = L('features/ghost-asura/translator.ts');
const { buildNarratives } = L('features/ghost-asura/narrative.ts');
const { GHOST_ASURA_UI } = L('features/ghost-asura/uiText.ts');
const { ASURA_WORDINGS } = L('features/ghost-asura/wordings.ts');
const { APPROVED_BY_RULE_ID } = L('features/ghost-asura/registry.ts');
const { ASURA_FORBIDDEN_TERMS } = L('lib/asura-display-alias.ts');

const backendIds = DUAL_SHENSHA_RULES.map(([id]) => id);
const backendNames = new Map(DUAL_SHENSHA_RULES);
const BAD_WORDS = /必定|一定會|註定|大凶|血光|死/;
const PLACEHOLDER = /此域暫無可用判讀|尚待確認|待校核/;
let checks = 0;
const existingBadWording = new Set();
const ok = (cond, msg) => { checks += 1; assert.ok(cond, msg); };

function narrativeFor(id, pillars = ['day']) {
  const record = {
    resultId: id, ruleId: id, originalName: backendNames.get(id) ?? id, matched: true, pillars,
    resultBatchId: 'B', motherVersion: 'V', backendStatus: 'MATCHED', reason: '', ruleVersion: 'V', source: 'x',
  };
  const [translated] = translateVerifiedRecords([record]);
  const [narrative] = buildNarratives([translated]);
  return { translated, narrative };
}

// 1. 唯一清單
ok(backendIds.length === 65, `後端編號應為 65，實際 ${backendIds.length}`);
ok(new Set(backendIds).size === 65, '後端編號不得重複');

// 2. 覆蓋率稽核：100%、缺漏 0、無錯誤對照
const audit = skill.auditAsuraCoverage(backendIds);
ok(audit.TOTAL_ASURA_IDS === 65, 'TOTAL_ASURA_IDS');
ok(audit.MAPPED_IDS === 65, `MAPPED_IDS：壞對照 ${audit.BROKEN_MAPPING_IDS.join(',')}`);
ok(audit.SKILL_ENTRY_IDS === 65, 'SKILL_ENTRY_IDS');
ok(audit.COMPLETE_IDS === 65, `COMPLETE_IDS：不完整 ${audit.INCOMPLETE_IDS.join(',')}`);
ok(audit.INCOMPLETE_IDS.length === 0 && audit.BROKEN_MAPPING_IDS.length === 0 && audit.missing.length === 0, '缺漏必須為 0');
ok(audit.coveragePercent === 100, 'Coverage 必須 100%');
ok(audit.reusedExisting + audit.autoGenerated === 65, '沿用＋生成必須等於 65');
ok(audit.reusedExisting === 19, `既有手寫話術應沿用 19 筆，實際 ${audit.reusedExisting}`);

// 3. Skill 條目：每個編號都有完整條目；沒有多餘條目；極性與既有導師話術一致
const toneToPolarity = { 福氣: 'positive', 動能: 'dynamic', 提醒: 'caution' };
for (const id of backendIds) {
  const entry = skill.ASURA_SKILL_ENTRIES[id];
  ok(entry, `缺 Skill 條目：${id}`);
  const missing = skill.missingFieldsOf(entry);
  ok(missing.length === 0, `Skill 條目不完整 ${id}：${missing.join(',')}`);
  ok(entry.asuraId === id && entry.sourceId === id, `asuraId／sourceId 必須等於規則編號：${id}`);
  ok(entry.displayName === APPROVED_BY_RULE_ID[id].displayName, `顯示名稱必須來自 registry：${id}`);
  ok([...entry.displayName].length === 4, `名稱必須四字：${id}`);
  ok(entry.version === skill.ASURA_SKILL_VERSION, `版本標記：${id}`);
  ok(entry.polarity === toneToPolarity[SHENSHA_TEACHER_READINGS[id].tone], `極性與既有導師話術不一致：${id}`);
}
const extra = Object.keys(skill.ASURA_SKILL_ENTRIES).filter((id) => !backendIds.includes(id));
ok(extra.length === 0, `Skill 有後端不存在的編號：${extra.join(',')}`);
ok(new Set(backendIds.map((id) => skill.ASURA_SKILL_ENTRIES[id].displayName)).size === 65, '顯示名稱不得重複');

// 4. RED 樣本＋正常對照：走完整條鏈（translator → narrative），不得出現佔位字
for (const id of ['tianyiDoctor', 'guoyin', 'xuetang', 'jiesha', 'guchen', 'yuede']) {
  const { narrative } = narrativeFor(id);
  ok(narrative.sealStatus === 'awakened' && narrative.hasApprovedWording === true, `${id} 應為覺醒且有核可話術`);
  for (const key of ['shortDeclaration', 'coreMeaning', 'battleSignificance', 'verdict']) {
    ok(narrative[key] && !PLACEHOLDER.test(narrative[key]), `${id}.${key} 不得空白或佔位：${narrative[key]}`);
  }
}

// 5. 全部 65 個編號 × 4 個柱位：完整、無佔位、無禁字、無原始名外洩、coreMeaning 一致
for (const id of backendIds) {
  const entry = skill.ASURA_SKILL_ENTRIES[id];
  const originalName = backendNames.get(id);
  for (const pillar of ['year', 'month', 'day', 'hour']) {
    const r = skill.resolveAsuraInterpretation(id, { pillars: [pillar] });
    ok(r.coreMeaning === entry.coreMeaning, `coreMeaning 不得被模板改動：${id}`);
    if (r.source === 'generated') ok(r.meaning.startsWith(entry.coreMeaning), `生成話術必須以 coreMeaning 為本：${id}/${pillar}`);
    const verdict = skill.validateAsuraCardContent(r);
    ok(verdict.valid, `驗證失敗 ${id}/${pillar}：${verdict.missing.join(',')}`);
    const { narrative, translated } = narrativeFor(id, [pillar]);
    const shown = [narrative.shortDeclaration, narrative.coreMeaning, narrative.battleSignificance, narrative.verdict];
    for (const text of shown) {
      ok(text && text.trim().length > 0, `空白欄位 ${id}/${pillar}`);
      ok(!PLACEHOLDER.test(text), `佔位字外洩 ${id}/${pillar}：${text}`);
      // 禁字／術數用語只擋「本次新生成」的話術；既有手寫話術依規格一字不改（另行回報）。
      if (r.source === 'generated') {
        ok(!BAD_WORDS.test(text), `禁字 ${id}/${pillar}：${text}`);
        const term = ASURA_FORBIDDEN_TERMS.find((t) => text.includes(t));
        ok(!term, `術數用語 ${term} 出現在生成話術 ${id}/${pillar}：${text}`);
      } else if (BAD_WORDS.test(text)) existingBadWording.add(id);
      // 把核可顯示名稱遮掉後，不得再出現後端原始名（原始名＝內部稽核用，不可當畫面文字）。
      const bare = text.split(translated.displayName).join('');
      ok(!bare.includes(originalName), `原始名外洩 ${id}（${originalName}）：${text}`);
    }
  }
}

// 6. 既有手寫話術一字不改（優先序第一）
let reusedChecked = 0;
for (const id of backendIds) {
  const name = APPROVED_BY_RULE_ID[id].displayName;
  const w = ASURA_WORDINGS[name];
  if (!w) continue;
  const r = skill.resolveAsuraInterpretation(id, { pillars: ['day'] });
  ok(r.source === 'existing', `既有話術應被沿用：${id}`);
  ok(r.meaningStrong === w.shortDeclaration && r.meaning === w.coreWarning && r.battleLine === w.battleSignificance && r.advice === w.verdict,
    `既有話術被改動：${id}`);
  reusedChecked += 1;
}
ok(reusedChecked === 19, `應沿用 19 筆，實際 ${reusedChecked}`);

// 7. 個人化只來自已驗證證據：同一編號不同柱位，柱位句不同、coreMeaning 相同；沒柱位證據不編造柱位句
{
  const a = skill.resolveAsuraInterpretation('guchen', { pillars: ['year'] });
  const b = skill.resolveAsuraInterpretation('guchen', { pillars: ['hour'] });
  ok(a.meaning !== b.meaning && a.coreMeaning === b.coreMeaning, '不同柱位應有不同個人化、同一核心');
  const none = skill.resolveAsuraInterpretation('guchen', { pillars: [] });
  ok(!none.meaning.includes('落在'), '沒有柱位證據時不得編造柱位句');
}

// 8. 錯誤契約
assert.throws(() => skill.resolveAsuraInterpretation('noSuchId', { pillars: ['day'] }), (e) => e.message === 'ASURA_SKILL_ENTRY_MISSING:noSuchId' && e.report && e.report.skillEntryFound === false);
checks += 1;
{
  const entry = skill.ASURA_SKILL_ENTRIES.guchen;
  const saved = entry.coreMeaning;
  entry.coreMeaning = '';
  try {
    assert.throws(() => skill.resolveAsuraInterpretation('guchen', { pillars: ['day'] }), (e) => e.message === 'ASURA_INTERPRETATION_INCOMPLETE:guchen' && e.report.missingFields.includes('coreMeaning'));
    checks += 1;
    const report = skill.diagnoseAsura('guchen', { pillars: ['day'] });
    ok(report.skillEntryFound && report.generationAttempted && !report.generationSuccess && report.reason.includes('coreMeaning'), '除錯報告欄位');
  } finally { entry.coreMeaning = saved; }
}
assert.throws(() => skill.assertAsuraCoverage(['a', 'b'], ['a']), (e) => e.message === 'ASURA_COVERAGE_MISMATCH:b');
checks += 1;
skill.assertAsuraCoverage(['a', 'b'], ['b', 'a']);
ok(!skill.validateAsuraCardContent({ asuraId: 'x', displayName: 'y', coreMeaning: 'c', meaningStrong: '', meaning: 'm', battleLine: 'b' }).valid, '缺 meaningStrong 必須 INVALID');
ok(!skill.validateAsuraCardContent({ asuraId: 'x', displayName: 'y', coreMeaning: 'c', meaningStrong: 's', meaning: GHOST_ASURA_UI.noReading, battleLine: 'b' }).valid, '佔位字必須 INVALID');
ok(skill.ASURA_SKILL_VERSION === 'ASURA_SKILL_V1.0' && skill.ASURA_SKILL_CHANGELOG.length >= 1, '版本與變更紀錄');

// 9. 原始碼守則：不再用名稱查話術；卡片元件不得有「暫無可用判讀」類回退
const narrativeSrc = fs.readFileSync(path.join(root, 'features/ghost-asura/narrative.ts'), 'utf8');
ok(!/ASURA_WORDINGS\s*\[/.test(narrativeSrc), 'narrative.ts 不得再用名稱索引 ASURA_WORDINGS');
ok(!/noReading|wordingGapHint/.test(narrativeSrc), 'narrative.ts 不得再使用缺話術佔位字');
const componentDir = path.join(root, 'features/ghost-asura/components');
for (const file of fs.readdirSync(componentDir).filter((f) => /\.tsx?$/.test(f))) {
  ok(!/暫無可用判讀|noReading|wordingGapHint/.test(fs.readFileSync(path.join(componentDir, file), 'utf8')), `前端元件不得有缺話術回退：${file}`);
}

// 10. 真實命盤全鏈：後端算盤 → 讀盤，每個覺醒印都必須有完整話術
const { calculateDualChart } = L('lib/dual-chart.ts');
const { buildGhostAsuraReading } = L('features/ghost-asura/index.ts');
const charts = [
  ['1974-06-28', '18:00', 'male'], ['1974-07-02', '03:30', 'female'], ['1985-03-05', '12:00', 'female'],
  ['1990-01-15', '08:30', 'male'], ['2000-12-31', '23:30', 'female'],
];
let awakenedTotal = 0;
for (const [birthDate, birthTime, gender] of charts) {
  const result = calculateDualChart({ birthDate, birthTime, gender, calendarType: 'solar', timezone: 'Asia/Taipei' });
  const reading = buildGhostAsuraReading({ result });
  const awakened = reading.items.filter((item) => item.sealStatus === 'awakened');
  awakenedTotal += awakened.length;
  for (const item of awakened) {
    for (const key of ['shortDeclaration', 'coreMeaning', 'battleSignificance', 'verdict']) {
      ok(item[key] && !PLACEHOLDER.test(item[key]), `真實命盤 ${birthDate} ${item.resultId}.${key} 佔位或空白：${item[key]}`);
    }
  }
}
ok(awakenedTotal > 0, '真實命盤至少要有覺醒印');

console.log(`PASS: ${checks} checks | ids=${audit.TOTAL_ASURA_IDS} entries=${audit.SKILL_ENTRY_IDS} complete=${audit.COMPLETE_IDS} `
  + `broken=${audit.BROKEN_MAPPING_IDS.length} reused=${audit.reusedExisting} generated=${audit.autoGenerated} coverage=${audit.coveragePercent}% `
  + `skill=${skill.ASURA_SKILL_VERSION} realAwakened=${awakenedTotal} existingWordingWithBannedWords=${[...existingBadWording].join(',') || 'none'}`);
