const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const source=fs.readFileSync('app/nameology/page.tsx','utf8');
const ast=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const fn=ast.statements.find(n=>n.name?.text==='readGuestSession');
let stored=null;
const ctx={exports:{},Date,sessionStorage:{getItem:()=>stored,removeItem:()=>{stored=null;}},GUEST_SESSION_KEY:'test',NAMEOLOGY_DAILY_SCHEMA_VERSION:'test'};
vm.runInNewContext(ts.transpileModule(fn.getText(ast)+'\nexports.read = readGuestSession;', {compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS}}).outputText,ctx);
const saved={schema:'test',savedAt:Date.now(),form:{name:'測試',birthDate:'1990-01-01',gender:'male',shichen:null},selectionConfirm:{gender:true}};
stored=JSON.stringify(saved); assert.equal(ctx.exports.read().form.name,'測試');
stored=JSON.stringify({...saved,savedAt:Date.now()-31*60*1000}); assert.equal(ctx.exports.read(),null); assert.equal(stored,null);
stored='{broken'; assert.equal(ctx.exports.read(),null);
stored=JSON.stringify({...saved,form:{...saved.form,shichen:12}}); assert.equal(ctx.exports.read(),null);
stored=JSON.stringify({...saved,schema:'obsolete'}); assert.equal(ctx.exports.read(),null);
assert.ok(source.includes('key={birthInputVersion}'));
assert.ok(source.includes('requestVersion !== requestVersionRef.current || requestInputKey !== nameologyInputKey(formRef.current)'));
assert.ok(source.includes("if (identity !== 'guest') return;"));
console.log('PASS: guest session validity, expiry, malformed data, field reset and stale-response guards');
