const fs = require('fs');

const read = (file) => fs.readFileSync(file, 'utf8');
const overlay = read('components/taiji/level-01/Level01Taiji.tsx');
const styles = read('components/taiji/level-01/level01.module.css');
const controller = read('components/taiji/level-01/Level01MotionController.ts');
const audio = read('components/taiji/level-01/Level01Audio.ts');
const haptics = read('components/taiji/level-01/Level01Haptics.ts');
const runtime = read('components/taiji/level-01/Level01Runtime.ts');
const quality = read('components/taiji/level-01/Level01QualityManager.ts');
const sensor = read('components/taiji/level-01/Level01SensorController.ts');
const errorBoundary = read('components/taiji/level-01/Level01ErrorBoundary.tsx');
const featureFlag = read('components/taiji/level-01/Level01FeatureFlags.ts');
const motionGame = read('components/taiji/level-01/Level01MotionGameEngine.ts');
const poseDriver = read('components/taiji/level-01/Level01PoseDriver.tsx');
const taijiSystem = read('components/TaijiSystem.tsx');
const sensory = read('components/taiji/level-01/Level01SensoryFeedback.ts');
const soundPreference = read('components/taiji/level-01/Level01SoundPreference.ts');
const soundPreferenceRoute = read('app/api/taiji-sound-preference/route.ts');

if (!overlay.includes('LEVEL_01 UI SCOPE LOCK')) throw new Error('level 01 scope lock comment is required');
if (overlay.includes('啟動太極') || styles.includes('.touchInvitation')) throw new Error('level 01 must never restore the obsolete explicit activation ritual');
if (!overlay.includes('data-level01-surface="dynamic-shadow"')) throw new Error('level 01 must keep its dynamic shadow surface');
if (overlay.includes('data-level01-layer="world-reference"') || overlay.includes('太極體感進度') || overlay.includes('第一層必要控制')) throw new Error('customer level 01 must stay visually clean without instructional HUD text');
if (styles.includes('.touchInvitation') || overlay.includes('輕觸太極，立即感受回應')) throw new Error('the obsolete explicit-start prompt must not remain in the automatic first-layer experience');
if (!overlay.includes('attemptAutomaticSensorStart()') || !controller.includes('canAutoStartLevel01Sensors()')) throw new Error('level 01 must start automatically when it becomes visible');
if (!taijiSystem.includes('IntersectionObserver') || !taijiSystem.includes("frameloop={taijiInView ? 'always' : 'never'}")) throw new Error('level 01 rendering and sensors must pause after the taiji leaves the viewport');
if (!taijiSystem.includes('const motionSplit = 0') || !taijiSystem.includes("if (displayLayer === 1)")) throw new Error('clicking or progressing inside level 01 must not reveal level 02 macro visuals');
if (overlay.includes("pose.motionGameEnabled ? '轉動手機，感受太極回應'")) throw new Error('the customer view must not stack a duplicate motion instruction over the taiji surface');
if (!taijiSystem.includes("params.get('taijiReview') === '1'") || taijiSystem.includes('const SHOW_LAYER_REVIEW_PANEL = true')) throw new Error('the 24-layer engineering review panel must stay hidden from the customer view');
if (!taijiSystem.includes('useTaijiJourneyGestures(wrapperRef, journeyRef)')) throw new Error('the explicit pinch journey from level 01 through level 24 must remain available');
if (!taijiSystem.includes('jumpJourney(journeyRef.current, TAIJI_DEPTH_MIN)') || taijiSystem.includes('jumpJourney(journeyRef.current, TAIJI_DEPTH_MAX)')) throw new Error('returning customers must stay on level 01 instead of restoring the level 24 satellite field');
if (!taijiSystem.includes('displayLayer === 1 && level01Controller.pose.motionGameEnabled') || taijiSystem.includes('displayLayer === 1 && showLayerReviewPanel && <Level01SpatialLightning')) throw new Error('level 01 lightning must follow the rollout flag, not the engineering review panel');
if (!taijiSystem.includes('const gestureStrikeActive = gestureStrikeAge >= 0') || !taijiSystem.includes('const striking = gestureStrikeActive || previewActive')) throw new Error('a short phone tap must latch one complete bounded lightning discharge');
if (!taijiSystem.includes('const topMain = leftMain.map') || !taijiSystem.includes('addLayeredBolt(bottomMain') || !taijiSystem.includes('addLayeredBolt(topMain')) throw new Error('all four cardinal photon-particle cores must visibly emit lightning toward the Taiji');
if (!taijiSystem.includes('Level01SpatialLightning({ active, origin, lowPower') || !taijiSystem.includes('group.rotation.set(0, 0, 0)') || taijiSystem.includes('origin={lightningOrigin} poseRef=')) throw new Error('the card-space lightning field must remain fixed while the Taiji rotates');
if (overlay.includes('cueNorth') || overlay.includes('cueEast') || overlay.includes('cueSouth') || overlay.includes('cueWest')) throw new Error('customer level 01 must not expose compass letters');
if (overlay.includes('data-level01-layer="energy-field"') || overlay.includes('data-level01-layer="balance-ring"')) throw new Error('level 01 must keep both decorative outer circles off the customer surface');
if (overlay.includes('COMBO_CUES') || overlay.includes('styles.combo')) throw new Error('customer level 01 must keep combo labels hidden while the engine continues scoring');
if (!overlay.includes('styles.chaseField') || !overlay.includes('追光目標') || !motionGame.includes('CHASE_HOLD_MS')) throw new Error('level 01 must expose a bounded four-direction chase-light challenge');
if (!overlay.includes('const motionGameActive = pose.motionGameEnabled;') || overlay.includes("pose.motionGameEnabled && pose.gameState !== 'IDLE'")) throw new Error('paired level 01 weapon cores must remain visible during automatic startup and fallback');
if (!overlay.includes('styles.chasePhotonNorth') || !overlay.includes('styles.chaseParticleEast') || !styles.includes('第一層四核心循環')) throw new Error('level 01 must keep the cardinal four-core photon-particle circulation');
if (!styles.includes('.chaseField .chaseLight { left: 50%; top: 97%') || !styles.includes('.chaseField .chaseCounterLight { left: 3%; top: 50%') || !styles.includes('.chaseField .chasePhotonNorth { left: 50%; top: 3%') || !styles.includes('.chaseField .chaseParticleEast { left: 97%; top: 50%')) throw new Error('the four level 01 cores must stay at north, east, south, and west');
if (!overlay.includes('key={`yin-${pose.motionGame.chase.direction}-${pose.motionGame.chase.hitId}`}') || !styles.includes('chaseCounterLightBreathe 1.15s')) throw new Error('the opposite dark yin-light must share the target direction, hit lifecycle, and breathing cadence');
if (styles.includes('--balance-angle') || styles.includes('--hold-angle')) throw new Error('removed outer-circle progress variables must not remain in level 01 styles');
if (overlay.includes('重新連接') || overlay.includes('改用拖曳') || !controller.includes('this.detachSensors()')) throw new Error('sensor loss must silently downgrade without exposing recovery controls over the taiji');
if (!overlay.includes('拖曳控制太極平衡') || !controller.includes('beginPointer') || !controller.includes('updatePointer')) throw new Error('desktop/touch fallback must preserve the same balancing objective');
if (overlay.includes('第一層必要控制') || overlay.includes('音效開') || overlay.includes('震動開')) throw new Error('customer level 01 must keep operating controls hidden');
if (!runtime.includes("| 'HOLDING'") || !runtime.includes("| 'SENSOR_LOST'") || !runtime.includes("| 'LOW_PERFORMANCE'")) throw new Error('complete game-state vocabulary is required');
if (!sensor.includes('SENSOR_SPIKE_THRESHOLD_DEG') || !sensor.includes('unwrapAngle') || !sensor.includes('SENSOR_DEAD_ZONE_DEG')) throw new Error('sensor fusion must reject spikes, unwrap headings, and apply a dead zone');
if (!quality.includes('QUALITY_RECOVER_HOLD_MS') || !quality.includes("this.quality = 'LOW'")) throw new Error('adaptive quality must include hysteresis and an immediate low-quality guard');
if (!audio.includes('DynamicsCompressorNode') || audio.includes('createOscillator(') || audio.includes('ambientOsc') || audio.includes('balanceOsc')) throw new Error('audio must use a limiter and must not create continuous ambient, motion, or balance oscillators');
if (!controller.includes('Level01RuntimeBoundary') || !errorBoundary.includes('getDerivedStateFromError')) throw new Error('level 01 errors must be contained locally');
if (!haptics.includes('gameEvent') || !haptics.includes('armedByUserGesture')) throw new Error('haptics must be event-driven and gesture-gated');
if (!styles.includes('aspect-ratio: 1') || !styles.includes("data-level01-quality='LOW'")) throw new Error('level 01 must reserve layout and expose quality-specific visual reductions');
if (overlay.includes("window.addEventListener('pointerdown'") || overlay.includes("window.addEventListener('touchstart'")) throw new Error('sensor permission must not be requested from an unrelated page gesture');
if (!featureFlag.includes('NEXT_PUBLIC_TAIJI_MOTION_GAME_V1') || !featureFlag.includes('taijiMotionGame')) throw new Error('motion game must remain behind its independent rollout and review flag');
if (!featureFlag.includes('return true;')) throw new Error('the mobile-validated level 01 experience must be enabled by default');
if (!overlay.includes('開始今日探索') || !controller.includes('toggleStaticMode') || !controller.includes('toggleHaptics')) throw new Error('V1 must preserve its delayed CTA and internal accessibility capabilities');
if (!motionGame.includes("'動'") || !motionGame.includes("'流'") || !motionGame.includes("'定'") || !motionGame.includes("'平衡'") || !motionGame.includes("'歸一'")) throw new Error('customer UI must use semantic motion language');
if (motionGame.includes('five-element-engine') || motionGame.includes('five-element-orb')) throw new Error('five-element motion signals must stay local and separate from formal analysis');
if (overlay.includes('用力甩手機')) throw new Error('unsafe phone-shaking copy is forbidden');
if (!controller.includes('unityReady') || !controller.includes('>= 1500')) throw new Error('unity must hold before the homepage exploration CTA appears');
if ((poseDriver.match(/useFrame\(/g) || []).length !== 1 || controller.includes('requestAnimationFrame(')) throw new Error('level 01 must use exactly one R3F frame-clock callback and no private RAF loop');
if (!taijiSystem.includes('Math.exp(-frameDelta / 0.5)') || !taijiSystem.includes('Math.exp(-frameDelta / 0.24)')) throw new Error('level 01 living cadence and scale handoff must remain delta-time smoothed');
if (sensor.includes('setState(') || sensor.includes('setPose(')) throw new Error('sensor event handlers may update refs/controllers only');
if (!taijiSystem.includes('First-layer game progress remains internal') || taijiSystem.includes('motionStageRank >= 3')) throw new Error('level 01 game progress must not reveal level 02-24 macro meshes or satellite fields');
if (!taijiSystem.includes('level01SurfaceEnergy') || !taijiSystem.includes('ballMat.envMapIntensity')) throw new Error('level 01 surface detail must respond through existing material uniforms, not extra geometry');
if (!styles.includes('@media (prefers-reduced-motion: reduce)') || !styles.includes('.particlePair { display: none; }')) throw new Error('reduced motion must stop level-01 particles');
if (!sensory.includes('TAIJI_PENTATONIC_HZ') || !sensory.includes('rotationBurstTimeline')) throw new Error('rotation feedback must use one bounded pentatonic audio-haptic profile');
if (!sensory.includes('TAIJI_ACTIVATION_FEEDBACK') || !haptics.includes('TAIJI_ACTIVATION_FEEDBACK')) throw new Error('first-touch motion and palm impact must share one deterministic entrance contract');
if (!audio.includes('playRotationPulse') || !audio.includes('playRotationBurst') || !audio.includes('only a visible lightning strike has sound')) throw new Error('rotation must stay silent while preserving the synchronized visual-haptic API');
if (!audio.includes('const ORIGIN_PAN') || !audio.includes('const impactAt = now + .17') || !audio.includes('panner.pan.linearRampToValueAtTime(0')) throw new Error('lightning audio must keep the selected core direction before converging on impact');
if (!controller.includes('this.armAudioFromUserGesture(true, initialStrikeOrigin)') || !controller.includes('if (playInitialLightning) this.audio.playLightningStrike(strikeOrigin)')) throw new Error('the first mobile gesture must play thunder from its selected origin after the AudioContext unlocks');
if (!audio.includes('const THUNDER_ASSETS') || !audio.includes("'/audio/taiji/lightning-strike.mp3'") || !audio.includes("'/audio/taiji/dry-thunder.mp3'") || !audio.includes("'/audio/taiji/loud-thunder.mp3'") || !audio.includes("'/audio/taiji/peals-of-thunder.mp3'") || !audio.includes('this.lightningVariantIndex += 1')) throw new Error('lightning must rotate through four licensed real thunder recordings');
if (audio.includes('Math.random(') || audio.includes('createBuffer(') || audio.includes('createOscillator(')) throw new Error('level 01 thunder must not synthesize noise, tones, or a repeating hum');
if (!audio.includes('First unlocked sound is the real lightning strike') || !audio.includes('No file is looped') && !read('public/audio/taiji/LICENSES.md').includes('No file is looped')) throw new Error('level 01 audio must stay silent between discrete real-thunder events');
for (const asset of ['lightning-strike.mp3', 'dry-thunder.mp3', 'loud-thunder.mp3', 'peals-of-thunder.mp3']) {
  const path = `public/audio/taiji/${asset}`;
  if (!fs.existsSync(path) || fs.statSync(path).size < 10000) throw new Error(`missing real thunder asset: ${asset}`);
}
if (!read('public/audio/taiji/LICENSES.md').includes('Pixabay Content License')) throw new Error('real thunder assets must keep auditable license provenance');
if (!haptics.includes('[5, 150, 17, 34, 24, 46, 9]')) throw new Error('the palm impact must land with the thunder and visual recoil timeline');
if (!haptics.includes('pulseRotation') || !haptics.includes('rotationBurstTimeline')) throw new Error('rotation haptics must share the audible burst timeline');
if (!controller.includes('this.audio.playRotationPulse(profile)') || !controller.includes('this.haptics.pulseRotation({ now')) throw new Error('rotation haptics must preserve the existing synchronized dispatch API while sound stays silent');
if (!controller.includes('this.audio.playChaseHit') || !controller.includes('this.haptics.playChaseHit')) throw new Error('chase-light hits must dispatch sound and palm feedback together');
if (!controller.includes('this.armAudioFromUserGesture()') || !controller.includes('this.haptics.armFromUserGesture()')) throw new Error('sound and haptics must be armed only from explicit customer controls');
if (!controller.includes('this.useFallback(true)')) throw new Error('pointer fallback must still arm enhancements from its explicit gesture');
if (!controller.includes('STATIC_ADVANCE_LOCK_MS') || !controller.includes('now - this.lastStaticAdvanceAt < STATIC_ADVANCE_LOCK_MS')) throw new Error('rapid static taps must not skip stages or stack sensory feedback');
if (overlay.includes('aria-pressed={pose.audioEnabled}')) throw new Error('hidden operating controls must not leave an invisible audio toggle in the customer DOM');
if (!controller.includes('suppressDirectional: this.featureEnabled && visualBurstTriggered') || !haptics.includes('!input.suppressDirectional')) throw new Error('a synchronized burst must not be overwritten by a same-frame directional haptic');
if (!soundPreference.includes('TAIJI_SOUND_VARIANTS') || !soundPreference.includes('MIN_SAMPLE_SIZE')) throw new Error('sound preference work must keep explicit candidates and a real sample threshold');
if (soundPreference.includes('sendBeacon') || soundPreference.includes('mediaDevices') || soundPreference.includes('getUserMedia')) throw new Error('sound preference must never capture or upload private audio');
if (soundPreference.includes('fetch(') && (!soundPreference.includes('JSON.stringify({ variant, field })') || !soundPreferenceRoute.includes('FIELD_SET') || !soundPreferenceRoute.includes('isRateLimited(request)'))) throw new Error('anonymous sound events must contain only allowlisted counters and pass server rate limiting');
if (controller.includes('private readonly soundVariant') || !controller.includes('this.soundVariant ?? this.soundPreference.resolveVariant()')) throw new Error('A/B assignment must be resolved lazily after an explicit customer interaction');
if (!controller.includes('recordNextStepCompleted()') || !overlay.includes('controller.recordNextStepCompleted()')) throw new Error('the next-step conversion signal must be recorded only from the explicit homepage CTA');
if (!audio.includes('this.blocked || !this.enabled')) throw new Error('disabled sound must not create or resume an AudioContext');
if (overlay.includes('styles.staticPanel')) throw new Error('customer level 01 must not expose static-mode instructions over the taiji');

console.log('Taiji Level 01 UI boundary passed');
