const fs = require('fs');
const overlay = fs.readFileSync('components/taiji/level-01/Level01Taiji.tsx', 'utf8');
const styles = fs.readFileSync('components/taiji/level-01/level01.module.css', 'utf8');
const controller = fs.readFileSync('components/taiji/level-01/Level01MotionController.ts', 'utf8');
const audio = fs.readFileSync('components/taiji/level-01/Level01Audio.ts', 'utf8');
const haptics = fs.readFileSync('components/taiji/level-01/Level01Haptics.ts', 'utf8');
if (!overlay.includes('LEVEL_01 UI SCOPE LOCK')) throw new Error('level 01 scope lock comment is required');
if (!overlay.includes('aria-label="啟用太極平衡感測"')) throw new Error('level 01 balance control must request sensors from a user gesture');
if (!overlay.includes('data-level01-surface="dynamic-shadow"')) throw new Error('level 01 trigger must remain the dynamic shadow surface');
if (!overlay.includes('data-level01-direction') || !overlay.includes('orientation-cue')) throw new Error('level 01 must keep its game-like orientation cue');
if (!styles.includes('visibility: hidden') || !styles.includes('explicit future restore')) throw new Error('direction letters must be hidden while their level-01 logic remains restorable');
if (overlay.includes('啟動太極') || styles.includes('.compassMark') || styles.includes('.startButton')) throw new Error('old compass/start control must not return');
if (styles.includes('水平儀')) throw new Error('visible level label must remain absent');
if (!styles.includes('--shadow-shift-x') || !styles.includes('--shadow-spread') || !styles.includes('--shadow-angle') || !styles.includes('.shadowGlow')) throw new Error('the level 01 control must remain a physics-driven shadow');
if (overlay.includes('輕觸啟動') || overlay.includes('shadowHint') || styles.includes('.shadowHint')) throw new Error('the level 01 trigger must not show a start-text prompt');
if (!overlay.includes('attemptAutomaticSensorStart')) throw new Error('the level 01 overlay must attempt gesture-free sensor start when supported');
if (!overlay.includes("window.addEventListener('pointerdown'") || !overlay.includes("window.addEventListener('touchstart'")) throw new Error('iOS fallback must accept any natural page touch without visible start copy');
if (!overlay.includes('particlePair') || !styles.includes('.particlePair') || !styles.includes('shadowPhotonDrift')) throw new Error('the level 01 shadow must keep its paired photon field');
if (!styles.includes('--pair-gap') || !styles.includes('--pair-angle')) throw new Error('the paired photons must reflect the filtered balance state');
if (!styles.includes('--shadow-rise') || !styles.includes('--shadow-depth')) throw new Error('the shadow must express depth from real horizontal tilt without visible labels');
if (!styles.includes('pointer-events: none') || !styles.includes('prefers-reduced-motion')) throw new Error('particles must not block touch and must respect reduced motion');
if (!controller.includes('this.haptics.armFromUserGesture()') || !haptics.includes('armedByUserGesture')) throw new Error('haptic feedback must remain behind a real user gesture');
if (!haptics.includes('lastDirectionAt') || !haptics.includes('motionEnergy >= 0.16') || !audio.includes('playTiltAccent')) throw new Error('direction feedback must keep its dead zone, cooldown, and quiet audio accent');
if (!audio.includes('playReentryCheerAccent') || !haptics.includes('scheduleReentryCheer') || !haptics.includes('reentryCheerTimer')) throw new Error('the one-shot re-entry cheer must keep aligned audio and haptic feedback');
if (!haptics.includes('scheduleVisualBurst') || !controller.includes('lastVisualBurstId') || !haptics.includes('safeTurns')) throw new Error('visual turns must map to a finite, throttled haptic rhythm');
if (!styles.includes('left: 50%') || !styles.includes('bottom: 7.5%') || !styles.includes('.cueSouth { opacity: 0; }') || !styles.includes('.balanceBubble')) throw new Error('dynamic shadow must stay in the ball bottom-centre seat');
console.log('Taiji Level 01 UI boundary passed');
