export const formEnglishCopy: Record<string, string> = {
  '西元': 'Gregorian',
  '（選填）': '(optional)', '完成': 'Complete', '已確認': 'Confirmed', '選填': 'Optional', '待填寫': 'Not entered', '待換算': 'Awaiting conversion', '待選擇': 'Not selected', '已完成': 'Complete',
  '萬年曆生日': 'Birth date', '出生日期（萬年曆）': 'Birth date', '出生地': 'Birthplace', '出生時辰': 'Birth time', '性別': 'Gender', '不確定': 'Unknown',
  '3. 性別': '3. Gender', '4. 出生地點': '4. Birthplace', '. 出生時辰': '. Birth time',
  '可以不填；填了，結果會用名字稱呼你': 'Optional; enter a name to personalize the results',
  '請先填寫姓名，至少 2 個字。': 'Enter a name with at least 2 characters.',
  '請先完成生日萬年曆推算。': 'Complete the birth-date conversion first.',
  '請點選性別，這欄還沒有確認。': 'Select a gender to confirm this field.',
  '用女性的算法。': 'Use the calculation rules for female charts.', '用男性的算法。': 'Use the calculation rules for male charts.',
  '國家，例如台灣': 'Country, e.g. Taiwan', '城市，例如台北': 'City, e.g. Taipei',
  '請確認出生國家與城市。': 'Confirm the country and city of birth.', '請先選擇出生時辰方式。': 'Choose whether your birth time is known.',
  '資料全部完成！點下方金色按鈕開始': 'All details complete! Select the gold button below to start',
  '完成上方欄位後，開始鍵會亮起金色光芒': 'Complete the fields above to highlight the start button in gold',
  '資料填寫': 'Your details', '依序完成欄位，易經才會開始運算': 'Complete the fields in order to begin the I Ching calculation',
  '開始分析': 'Start analysis', '運算中...': 'Calculating...',
  '不知道也沒關係，先算得出來的部分；之後補上時辰會更完整。': 'If the time is unknown, start with the available information. Adding it later makes the chart more complete.',
  '點下去會展開 12 張時辰卡，直接點選，不需手打。': 'Open the 12 birth-time cards and choose one; no typing needed.',
  '👇 請點選你的出生時辰': '👇 Choose your birth-time period', '標準十二時辰': '12 traditional time periods',
  '✓ 已選擇：': '✓ Selected:', '）——選錯可直接點別張更換': ') — Select another card to change it',
  '還沒選——下面 12 張點一張就好。不確定的話，回上面選「不知道出生時辰」也算得出來。': 'Choose one of the 12 cards below. If unsure, select “Birth time unknown” above to continue with available information.',
  '深夜': 'Late night', '夜半': 'Midnight', '半夜': 'Middle of the night', '凌晨': 'Before dawn', '清晨': 'Early morning', '早上': 'Morning', '上午': 'Late morning', '中午': 'Noon', '午後': 'After noon', '下午': 'Afternoon', '傍晚': 'Evening', '晚上': 'Night', '夜晚': 'Night',
  '民間說法：細膩穩定，重視秩序與安全感。': 'Folk belief: attentive and steady, valuing order and a sense of security.',
  '民間說法：自由直覺，重視感受與關係中的空間。': 'Folk belief: free-spirited and intuitive, valuing feelings and personal space in relationships.',
  '民間說法：理性與感性交織，關係節奏需要彈性。': 'Folk belief: reason and emotion intertwine, calling for flexibility in the rhythm of a relationship.',
  '民間說法：直接熱情，在關係裡會主動承擔與推進。': 'Folk belief: direct and enthusiastic, taking responsibility and initiative in relationships.',
  '下一步：填第二位': 'Next: person 2', '下一步：確認資料': 'Next: review details',
  '正在整理配對結果…': 'Preparing your relationship results…', '查看今日結果': 'View today’s results', '立即開始': 'Start now',
  '目前進度': 'Your progress', '先填第一位': 'Enter person 1', '再填第二位': 'Enter person 2', '確認後開始配對': 'Review and start', '確認': 'Review',
  '不知道': 'Unknown', '不知道（以三柱計算）': 'Unknown (three pillars)',
  '未填': 'Not entered', '未換算完成': 'Conversion incomplete',
  '名字、生日、血型都沒問題，就可以開始。這一步讓你安心確認，不怕按太快。': 'Check the names, birth dates and blood types before starting. Take a moment to review the details.',
  '請先輸入第一位姓名，至少 2 個字。': 'Enter person 1’s name (at least 2 characters).',
  '請先輸入第二位姓名，至少 2 個字。': 'Enter person 2’s name (at least 2 characters).',
  '請先完成第一位的萬年曆生日推算。': 'Complete person 1’s birth-date conversion.',
  '請先完成第二位的萬年曆生日推算。': 'Complete person 2’s birth-date conversion.',
  '請點選第一位性別。': 'Select person 1’s gender.', '請點選第二位性別。': 'Select person 2’s gender.',
  '請先把兩位資料填完整。': 'Complete the details for both people.',
  '配對分析失敗，請稍後再試。': 'The relationship analysis failed. Please try again later.',
  '配對分析等候時間過長，請稍後再試。': 'The relationship analysis timed out. Please try again later.',
  '目前無法連線到配對服務，請稍後再試。': 'The relationship service cannot be reached. Please try again later.',
  '🔮 姓名乃人和磁場之五格載體：後端依正體字典筆畫計算五格，再與生日、時辰交叉比對。': '🔮 In this tradition, a name represents five grids of interpersonal energy. The backend calculates these grids using traditional-character stroke counts and cross-checks them against the birth date and time.',
  '🪐 八字與紫微斗數的年、月、日、時四柱在後端逐字核對，一致才往下解讀。': '🪐 The backend checks the year, month, day and hour pillars in Ba Zi and Zi Wei character by character. Interpretation proceeds only when they match.',
  '第一位資料': 'Person 1 details', '第二位資料': 'Person 2 details',
  '先輸入第一位的姓名、生日、時辰、血型和性別。時辰不知道可直接略過。': 'Enter the first person’s name, birth date, birth time, blood type and gender. You may skip an unknown birth time.',
  '接著輸入第二位。時辰知道就選十二時辰，不知道可直接略過。': 'Next, enter the second person’s details. Choose a birth-time period if known, or skip it if unknown.',
  '配對資料': 'Relationship details', '1. 姓名': '1. Name',
  '2. 出生日期（萬年曆）': '2. Birth date', '3. 出生時辰（可略過）': '3. Birth time (optional)',
  '4. 血型': '4. Blood type', '5. 性別': '5. Gender',
  '請輸入姓名，至少 2 個字': 'Enter a name (at least 2 characters)',
  '⚠️ 請填寫姓名，至少 2 個字。': 'Please enter a name with at least 2 characters.',
  '⚠️ 請先完成生日資料。': 'Please complete the birth date.',
  '⚠️ 請點選性別，這欄還沒有確認。': 'Please select a gender to confirm this field.',
  '我知道出生時辰': 'I know the birth time', '不知道出生時辰': 'Birth time unknown',
  '展開十二時辰，點選正確時辰後以完整四柱配對。': 'Choose the correct two-hour period to use all four pillars.',
  '直接用八字三柱基礎配對；時柱不推定。': 'Use the year, month and day pillars. No hour pillar will be guessed.',
  '知道時辰可生成完整四柱八字；不知道也可以直接選不知道，系統只用年、月、日三柱，不會假裝補出時柱。': 'A known birth time enables all four pillars. If it is unknown, choose unknown; only the year, month and day pillars will be used.',
  '我知道血型': 'I know the blood type', '不知道血型': 'Blood type unknown',
  '展開 A、B、O、AB，將血型納入配對。': 'Choose A, B, O or AB to include blood type in the reading.',
  '仍可繼續配對；血型維度改為中性，不假裝已知。': 'Continue with a neutral blood-type factor instead of assuming a blood type.',
  '🧬 血型只用在「相處共鳴指數」的固定規則裡；不知道就用預設值，不會影響八字與五元素。': 'Blood type is used only in the relationship resonance rules. An unknown blood type uses the default value and does not affect Ba Zi or the five elements.',
  '✦ 性別不會改變八字四柱；紫微命盤與相處共鳴指數會參考它。': 'Gender does not change the Ba Zi pillars. It is used in the Zi Wei chart and relationship resonance index.',
  '女性': 'Female', '男性': 'Male', '用來修飾外在表現。': 'Used to describe outward expression.',
  '只做外在呈現修飾。': 'Used for outward presentation.', '已選': 'Selected', '點選': 'Select',
  '細膩穩定，重視秩序與安全感。': 'Attentive and steady, with an emphasis on order and security.',
  '自主鮮明，節奏感強，較有個人風格。': 'Independent, with a distinctive rhythm and personal style.',
  '理性感性並存，觀察力與距離感並行。': 'Combines reason and emotion, observation and personal distance.',
  '主動直接，行動力高，帶動感明顯。': 'Proactive and direct, with energy for action and initiative.',
  'A 型': 'Type A', 'B 型': 'Type B', 'AB 型': 'Type AB', 'O 型': 'Type O',
  '我知道了 ✗': 'Got it ✗', '第一位': 'Person 1', '第二位': 'Person 2',
  '確認資料後開始配對': 'Confirm the details to start', '最後確認': 'Final check',
  '姓名': 'Name', '姓名：': 'Name:', '西元生日：': 'Gregorian birth date:', '血型：': 'Blood type:',
  '性別：': 'Gender:', '出生時辰：': 'Birth time:', '上一步': 'Back', '下一步': 'Next',
  '重新輸入': 'Start again', '匯出配對報告': 'Print relationship report',
  '子時': 'Zi (子)', '丑時': 'Chou (丑)', '寅時': 'Yin (寅)', '卯時': 'Mao (卯)',
  '辰時': 'Chen (辰)', '巳時': 'Si (巳)', '午時': 'Wu (午)', '未時': 'Wei (未)',
  '申時': 'Shen (申)', '酉時': 'You (酉)', '戌時': 'Xu (戌)', '亥時': 'Hai (亥)',
};
