/** Display-only translations. Never use translated text as calculation input. */
export const homeEnglishCopy: Record<string, string> = {
  '易經聲音歌曲': 'I Ching-inspired music', '生成一首歌': 'Create a song',
  '自我人格分裂': 'Different sides of yourself', '跟你自我對話': 'A conversation with yourself',
  '這首歌，是你人格分裂後，每一個自己共同唱出的內心獨白。🎁 拆開有禮：一首只屬於你生辰卦象的靈魂之歌。': 'Hear the different sides of yourself in a personal song inspired by the hexagram associated with your birth details.',
  '免費生成': 'Free generation', '依生辰': 'Based on birth details', '可重聽': 'Listen again', '立即生成歌曲': 'Create a song',
  '需姓名': 'Name needed', '約 30 秒': 'About 30 seconds', '只需數字': 'Digits only',
  '需生辰': 'Birth details needed', '看長期方向': 'Long-term themes',
  '正在開啟紫微…': 'Opening chart…', '立即開啟紫微': 'Open Zi Wei chart',
  '易經 · 八字命盤': 'I Ching · Ba Zi chart', '易經八字命盤': 'Ba Zi birth chart',
  '// 八字四柱 · 五元素補強 · 相生相剋': '// Four pillars · Five elements · Element relationships',
  '獨立八字排盤，整理四柱、藏干、十神、旺衰、大運與流年。🎁 拆開有禮：同一張盤的兩種聲音——溫柔的與神祕的，各給你一份。': 'Explore the four pillars, hidden stems, ten gods, element strength, major cycles and annual cycles. Read two interpretations of the same chart: gentle and mysterious.',
  '正統排盤': 'Traditional chart methods', '立即開啟命盤': 'Open birth chart',
  '易經 · 星空人格': 'I Ching · Zodiac personality', '易經西洋星座': 'Western zodiac',
  '// 出生年月日 · 十二星座 · 本週提醒': '// Birth date · Twelve signs · Weekly prompts',
  '輸入出生年月日，獨立判定十二星座，整理人格特質、優勢、忽略點與本週提醒。🎁 拆開有禮：你的星座×易經卦象，一週剛剛好的提醒。': 'Enter your birth date to find your zodiac sign and explore personality themes, strengths, blind spots and weekly prompts inspired by the zodiac and I Ching.',
  '開始星座分析': 'Explore your zodiac sign', '一抽即見': 'Reveal with a tap',
  '免費體驗': 'Free experience', '可旋轉': 'Rotate the model', '非付費牆': 'No paywall',
  '快速切換': 'Quick navigation', '功能': 'Features',
  '順天而行，': 'Follow the natural way,', '感恩的心': 'with a grateful heart',
  '逆天而行': 'Against the natural way',
  '桃花・紅鸞心動': 'Romance · Red Luan',
  '抽出心動月份、對象類型與相遇提示。': 'Discover romance months, partner archetypes and meeting prompts.',
  '抽出我的心動月份': 'Discover my romance months',
  '易經 · 靈魂雙星配對': 'I Ching · Relationship reading',
  '易經靈魂配對': 'I Ching relationship reading',
  '// 雙人命盤 · 相處節奏 · 互補點分析': '// Two charts · Relationship rhythms · Complementary traits',
  '輸入兩位資料，分析相處頻率、吸引力、溝通模式與命定互補關係。🎁 拆開有禮：兩顆心的合卦，和一句誰最懂誰的答案。': 'Enter two people’s details to explore relationship rhythms, attraction, communication and complementary traits. Reveal a shared hexagram and a reflection on mutual understanding.',
  '立即開啟配對': 'Explore a relationship',
  '易經 · 姓名決策系統': 'I Ching · Name exploration', '易經姓名學': 'I Ching name reading',
  '// 臺灣字典 · 取名意境 · 易經卜卦判定': '// Taiwan character dictionary · Name imagery · I Ching interpretation',
  '以臺灣字典固定部首、筆畫與取名意境，最後只留下今天最需要改變的一個方向。🎁 拆開有禮：你名字裡藏著一句沒人說破的溫度話。': 'Explore character radicals, stroke counts and name imagery using a Taiwan dictionary, with one direction to reflect on today and a personal message inspired by your name.',
  '開啟姓名決策': 'Explore a name',
  'CARD 01 · 數字好壞速測': 'CARD 01 · Number reading', '易經論數字': 'I Ching number reading',
  '// 4 / 6 / 8 / 10 碼 · 即時判定': '// 4 / 6 / 8 / 10 digits · Immediate reading',
  '輸入 2 到 10 碼，易經立即整理吉凶傾向與今日行動。🎁 拆開有禮：你的數字會起出一支專屬卦，六十四格裡就這一格是你。': 'Enter 2–10 digits to explore traditional auspiciousness patterns and an action for today. Reveal the I Ching hexagram derived from your numbers.',
  '立即開始': 'Get started', '易經 · 紫微斗數命盤': 'I Ching · Zi Wei Dou Shu chart',
  '易經紫微斗數': 'Zi Wei Dou Shu', '// 命宮主軸 · 三方四正 · 年度方向': '// Life palace · Palace relationships · Annual themes',
  '依出生資料整理命宮主軸，先看懂長期方向，再交給 易經做精華判定。🎁 拆開有禮：你的特殊格局名稱，和一句「我真的懂你」。': 'Use birth details to explore life-palace themes and long-term direction, followed by an I Ching summary. Reveal your traditional chart-pattern name and a personal reflection.',
  '28 星宿・四象收藏': '28 lunar mansions · Four celestial symbols', '星宿神獸卡片': 'Celestial creature cards',
  '二十八星宿分類各有本體與幼子形態，另有四隻四象守護獸。瀏覽卡片，認識各自的守護特質。': 'Each of the 28 lunar mansion categories has an adult and a young form, alongside four separate celestial guardians. Browse the cards and discover their guardian traits.',
  '查看 60 種神獸': 'Explore 60 creatures', '四維 · 超立方': 'Four dimensions · Hypercube',
  '立體太極模型工作室': '3D Tai Chi model studio', '空心太極包方形核心，方圓緊貼，進入四維。': 'Explore a hollow Tai Chi form surrounding a square core, where circles meet squares in a four-dimensional visualization.',
  '打開模型工作室': 'Open the model studio',
  '分享給朋友': 'Share with a friend', 'LINE 好友支持': 'Connect on LINE',
  '加 LINE 好友，免費立即體驗 VIP': 'Add us on LINE for a free VIP trial',
  '加入官方 LINE 好友，取得配對、人格、數字好壞與深度洞察的免費體驗入口。': 'Add the official LINE account to access free trials of relationship, personality, number and insight readings.',
  '加好友領體驗': 'Add on LINE',
  'CARD 01 · 古老塔羅牌': 'CARD 01 · Traditional tarot', '古老塔羅牌': 'Traditional tarot',
  '// 78 張牌庫 · 真洗牌 · 親手抽牌': '// 78 cards · Shuffle · Draw your own cards',
  '先固定一個問題，再親手抽牌；易經最後只留下最重要的一句判定。🎁 拆開有禮：三張牌直接回答你的問題，附上明確的機率數字。': 'Focus on a question and draw your cards. Read an I Ching summary and a three-card interpretation with the app’s displayed probability figures.',
  '觸碰抽牌': 'Tap to draw',
  '免費': 'Free', '親手抽牌': 'Draw your own cards', '免登入': 'No sign-in', '需生日': 'Birth date needed',
  '約 20 秒': 'About 20 seconds', '免費瀏覽': 'Free to browse', '60 種可看': '60 creatures', '先看再玩': 'Browse, then play',
};
