create table if not exists public.like_counter (
  id text primary key check (id = 'global'),
  total_count bigint not null default 630628 check (total_count >= 630628),
  updated_at timestamptz not null default now()
);

insert into public.like_counter (id, total_count)
values ('global', 630628)
on conflict (id) do nothing;

alter table public.like_counter enable row level security;

revoke all on table public.like_counter from anon, authenticated;

create table if not exists public.like_logs (
  id bigint generated by default as identity primary key,
  counter_id text not null default 'global' references public.like_counter(id) on delete cascade,
  device_id text,
  user_id uuid,
  ip_hash text,
  liked_at timestamptz not null default now(),
  check (device_id is not null or user_id is not null)
);

create unique index if not exists like_logs_counter_device_unique
on public.like_logs (counter_id, device_id)
where device_id is not null;

create unique index if not exists like_logs_counter_user_unique
on public.like_logs (counter_id, user_id)
where user_id is not null;

alter table public.like_logs enable row level security;

revoke all on table public.like_logs from anon, authenticated;

create or replace function public.record_ai_like(
  requested_device_id text,
  requested_ip_hash text default null,
  requested_user_id uuid default null
)
returns table (
  total_count bigint,
  did_like boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  did_record boolean;
begin
  if requested_device_id is null or requested_device_id !~ '^[a-zA-Z0-9:_-]{16,128}$' then
    raise exception 'Invalid device id';
  end if;

  insert into public.like_counter (id, total_count)
  values ('global', 630628)
  on conflict (id) do nothing;

  with recorded as (
    insert into public.like_logs (counter_id, device_id, user_id, ip_hash)
    values ('global', requested_device_id, requested_user_id, requested_ip_hash)
    on conflict (counter_id, device_id) where device_id is not null do nothing
    returning 1
  )
  select exists(select 1 from recorded) into did_record;

  if did_record then
    update public.like_counter
    set total_count = total_count + 1,
        updated_at = now()
    where id = 'global';
  end if;

  return query
  select counters.total_count, did_record
  from public.like_counter as counters
  where counters.id = 'global';
end;
$$;

revoke all on function public.record_ai_like(text, text, uuid) from public, anon, authenticated;
grant usage on schema public to service_role;
grant execute on function public.record_ai_like(text, text, uuid) to service_role;
