/**
 * 鬼魅阿修羅 Skill — 覆蓋率稽核。
 *
 * 唯一清單由呼叫端傳入（正式用 lib/dual-chart-iching-shensha.ts 的 DUAL_SHENSHA_RULES 編號）；
 * 這裡不自己維護第二份編號表。
 */
import { APPROVED_BY_RULE_ID } from '../registry';
import { ASURA_SKILL_ENTRIES, missingFieldsOf } from './entries';
import { AsuraSkillError, diagnoseAsura, resolveAsuraInterpretation, type AsuraDebugReport } from './resolver';
import type { GhostAsuraPillarKey } from '../types';

const ALL_PILLARS: GhostAsuraPillarKey[] = ['year', 'month', 'day', 'hour'];

export interface AsuraCoverageAudit {
  TOTAL_ASURA_IDS: number;
  /** registry 有核可名稱（編號→名稱對得上）。 */
  MAPPED_IDS: number;
  SKILL_ENTRY_IDS: number;
  COMPLETE_IDS: number;
  INCOMPLETE_IDS: string[];
  /** 編號在 registry 沒有核可名稱，或名稱與別的編號重複。 */
  BROKEN_MAPPING_IDS: string[];
  missing: string[];
  reusedExisting: number;
  autoGenerated: number;
  coveragePercent: number;
  reports: AsuraDebugReport[];
}

export function auditAsuraCoverage(backendIds: readonly string[]): AsuraCoverageAudit {
  const ids = [...new Set(backendIds)];
  const nameOwners = new Map<string, string[]>();
  for (const id of ids) {
    const name = APPROVED_BY_RULE_ID[id]?.displayName;
    if (name) nameOwners.set(name, [...(nameOwners.get(name) ?? []), id]);
  }
  const broken = ids.filter((id) => {
    const name = APPROVED_BY_RULE_ID[id]?.displayName;
    return !name || (nameOwners.get(name)?.length ?? 0) > 1;
  });

  const incomplete: string[] = [];
  const reports: AsuraDebugReport[] = [];
  let reused = 0;
  let generated = 0;
  for (const id of ids) {
    let ok = missingFieldsOf(ASURA_SKILL_ENTRIES[id]).length === 0;
    // 每個柱位都要能產出完整話術（柱位只影響模板版本與柱位句，不得影響完整性）。
    for (const pillar of ALL_PILLARS) {
      try {
        const r = resolveAsuraInterpretation(id, { pillars: [pillar] });
        if (pillar === 'year') r.source === 'existing' ? (reused += 1) : (generated += 1);
      } catch (error) {
        ok = false;
        if (error instanceof AsuraSkillError && error.report) reports.push(error.report);
        else throw error;
        break;
      }
    }
    if (!ok) incomplete.push(id);
  }
  for (const id of ids) if (incomplete.includes(id) && !reports.some((r) => r.asuraId === id)) reports.push(diagnoseAsura(id, { pillars: ['year'] }));

  const complete = ids.length - incomplete.length;
  return {
    TOTAL_ASURA_IDS: ids.length,
    MAPPED_IDS: ids.length - broken.length,
    SKILL_ENTRY_IDS: ids.filter((id) => ASURA_SKILL_ENTRIES[id]).length,
    COMPLETE_IDS: complete,
    INCOMPLETE_IDS: incomplete,
    BROKEN_MAPPING_IDS: broken,
    missing: [...new Set([...incomplete, ...broken])],
    reusedExisting: reused,
    autoGenerated: generated,
    coveragePercent: ids.length === 0 ? 0 : Math.round((complete / ids.length) * 10000) / 100,
    reports,
  };
}

/** 命中數必須等於解析成功數，否則丟 ASURA_COVERAGE_MISMATCH（附缺漏清單）。 */
export function assertAsuraCoverage(hitIds: readonly string[], resolvedIds: readonly string[]): void {
  const resolved = new Set(resolvedIds);
  const missing = [...new Set(hitIds)].filter((id) => !resolved.has(id));
  if (new Set(hitIds).size !== new Set(resolvedIds).size || missing.length > 0) {
    throw new AsuraSkillError('ASURA_COVERAGE_MISMATCH', missing.join(',') || '(count)');
  }
}
